import json

from sqlalchemy import create_engine, inspect, text

import o


class Db(o.Service):
	conn_key = 'DB_CONN'

	dialect = dict(
		AUTOINCREMENT = dict(
			sqlite     = 'AUTOINCREMENT',
			postgresql = 'GENERATED BY DEFAULT AS IDENTITY',
			mysql      = 'AUTO_INCREMENT',
		),

		INT  = dict( sqlite='INTEGER', postgresql='INTEGER', mysql='INTEGER' ),
		STR  = dict( sqlite='TEXT',    postgresql='TEXT',    mysql='TEXT'    ),
		BOOL = dict( sqlite='INTEGER', postgresql='BOOLEAN', mysql='BOOLEAN' ),
		DICT = dict( sqlite='TEXT',    postgresql='JSONB',   mysql='JSON'    ),
		LIST = dict( sqlite='TEXT',    postgresql='JSONB',   mysql='JSON'    ),
		JSON = dict( sqlite='TEXT',    postgresql='JSONB',   mysql='JSON'    ),
	)

	# ======================================================================
	# PRIVATE METHODS
	# ======================================================================

	# Assert that connection is present
	# ----------------------------------------------------------------------
	def _assert_connection(self):
		if not self.conn:
			raise RuntimeError('No active connection')

	# Returns 'id' or 'key' based on type. Else – error
	# ----------------------------------------------------------------------
	def _get_identifier(self, id_or_key):
		if   isinstance(id_or_key, int): identifier = 'id'
		elif isinstance(id_or_key, str): identifier = 'key'
		else:
			raise TypeError(f'Invalid identifier type: {type(id_or_key)}')

		return identifier

	# Precompiles parts of query: where and params for single item actions
	# ----------------------------------------------------------------------
	def _shortcuts(self, id_or_key):
		identifier = self._get_identifier(id_or_key)
		where      = f'{identifier} = :{identifier}'
		params     = {identifier: id_or_key}
		
		return where, params

	# ======================================================================
	# PUBLIC METHODS
	# ======================================================================

	# Initialize
	# ----------------------------------------------------------------------
	def initialize(self):
		print('type(o.Conf)', type(o.Conf))
		self.db_url  = o.Conf[self.conn_key] if self.conn_key in o.Conf else None
		self.engine  = None
		self.conn    = None
		self.tx      = None

		if self.db_url:
			self.connect()

		self.a = o.AsyncDb

	# Translate types and other varieties to engine-specific sql
	# ----------------------------------------------------------------------
	def to_sql(self, x):
		if x is None or x is type(None):
			raise TypeError(f'NoneType is not a valid SQL column type: {x}')

		if isinstance(x, str):
			key = x.upper()
		else:
			x   = o.Type(x)
			key = x.to_string().upper()
			if key not in Db.dialect:
				return 'TEXT'

		return Db.dialect[key][self.engine.dialect.name] if key in Db.dialect else x

	# Translate python value to sql literal
	# ----------------------------------------------------------------------
	def to_sql_value(self, value):
		out = None

		if value is None:
			out  = 'NULL'
		elif isinstance(value, (dict, list)):
			text = json.dumps(value, ensure_ascii=False)
			text = text.replace('"', '""')
			out  = f'"{text}"'
		elif isinstance(value, str):
			text = value.replace('"', '""')
			out  = f'"{text}"'
		elif isinstance(value, bool):
			out  = '1' if value else '0'
		else:
			out = str(value)

		return out

	# ======================================================================
	# CONNECTION METHODS
	# ======================================================================

	# Connect
	# ----------------------------------------------------------------------
	def connect(self, db_url=None):
		if db_url is None:
			if self.db_url is None:
				raise KeyError(f'To connect: pass db url to o.Db.connect or set `o.Conf.{self.conn_key}`.')
		else:
			self.db_url = db_url

		if self.conn:
			self.disconnect()

		self.engine = create_engine(self.db_url, echo=False)
		self.conn   = self.engine.connect()
		self.print(f'Connected to database')
		
		return self

	# Disconnect
	# ----------------------------------------------------------------------
	def disconnect(self):
		if self.tx     : self.tx.rollback()
		if self.conn   : self.conn.close()
		if self.engine : self.engine.dispose()

		self.engine = None
		self.conn   = None
		self.tx     = None
		self.print(f'Disconnected from database')

		return self

	# ======================================================================
	# TRANSACTION METHODS
	# ======================================================================

	def tx_begin(self):
		self._assert_connection()
		if not self.tx:
			self.tx = self.conn.begin()
		else: self.print('WARNING: transaction is already present')

	def tx_end(self):
		self._assert_connection()
		if self.tx:
			self.tx.commit()
			self.tx = None
		else: self.print('WARNING: transaction is not present')

	def tx_undo(self):
		self._assert_connection()
		if self.tx:
			self.tx.rollback()
			self.tx = None
		else: self.print('WARNING: transaction is not present')

	# ======================================================================
	# TABLE METHODS
	# ======================================================================

	# Get all table names from current database.
	# ----------------------------------------------------------------------
	def get_table_names(self):
		self._assert_connection()

		inspector = inspect(self.engine)
		names     = inspector.get_table_names()

		return names

	# Create table
	# ----------------------------------------------------------------------
	def create_table(self, table, definition):

		offset        = 10
		cols          = []
		INT           = self.to_sql(int)
		STR           = self.to_sql(str)
		AUTOINCREMENT = self.to_sql('AUTOINCREMENT')

		ID  = 'id'.ljust(offset)
		KEY = 'key'.ljust(offset)

		cols.append(f'{ID} {INT} PRIMARY KEY {AUTOINCREMENT}')
		cols.append(f'{KEY} {STR} UNIQUE')

		for f in definition:
			name       = f['name']
			py_type    = f['type'].get_origin() if isinstance(f['type'], o.Type) else f['type']

			sql_type    = self.to_sql(py_type)
			sql_notnull = '' if f['nullable'] else 'NOT NULL'

			col = f'{name:<{offset}} {sql_type} {sql_notnull}'
			cols.append(col)

		cols_sql = ',\n\t'.join(cols)
		query    = f'CREATE TABLE IF NOT EXISTS {table} (\n\t{cols_sql}\n)'

		self.execute(query)

	# Drop table
	# ----------------------------------------------------------------------
	def drop_table(self, table):
		self._assert_connection()

		if not self.has_table(table):
			return False

		query = f'DROP TABLE {table}'
		self.execute(query)

		return True

	# Drop table
	# ----------------------------------------------------------------------
	def drop_all_tables(self):
		for table in self.get_table_names():
			self.drop_table(table)

	# Checks if table exists
	# ------------------------------------------------------------------
	def has_table(self, name):
		return name in self.get_table_names()

	# Debug dump table
	# ------------------------------------------------------------------
	def debug_table(self, table):
		self._assert_connection()
		rows = self.get_all(f'SELECT * FROM {table}')
		print('-' * 70)
		print(f'Table: `{table}`')
		print('-' * 70)
		for r in rows:
			print(r)
		print('-' * 70)

	# Debug sql statement
	# ------------------------------------------------------------------
	def debug_sql(self, query, **params):
		print('-' * 70)
		stmt = text(query).bindparams(**params)
		compiled = stmt.compile(
			dialect=self.engine.dialect,
			compile_kwargs={'literal_binds': True}
		)
		print(compiled)

	# ======================================================================
	# RECORD METHODS
	# ======================================================================
	
	def get_keys(self, table):
		rows = self.get_all(f'SELECT key FROM {table} WHERE key IS NOT NULL')
		return [row['key'] for row in rows]

	def set(self, table, **params):
		if params.get('id', None) is not None:
			name_value_pairs = ', '.join(f'{k} = :{k}' for k in params.keys() if k != 'id')
			query  =  f'UPDATE {table} SET {name_value_pairs} WHERE id = :id'
		else:
			names  = ', '.join(params.keys())
			values = ', '.join(f':{k}' for k in params.keys())
			query  = f'INSERT INTO {table} ({names}) VALUES ({values})'

		result = self.execute(query, **params)
		return result.lastrowid

	def get_one(self, query, **params):
		row = self.execute(query, **params).fetchone()
		return dict(row._mapping) if row else None

	def get_all(self, query, **params):
		rows = self.execute(query, **params).fetchall()
		return [dict(r._mapping) for r in rows]

	def get(self, table, id_or_key):
		where, params = self._shortcuts(id_or_key)
		return self.get_one(f'SELECT * FROM {table} WHERE {where}', **params)

	def has(self, table, id_or_key):
		return self.get(table, id_or_key) is not None

	def delete(self, table, id_or_key):
		where, params = self._shortcuts(id_or_key)
		result = self.execute(f'DELETE FROM {table} WHERE {where}', **params)
		return result.rowcount

	def execute(self, query, **params):
		self.debug_sql(query, **params)
		self._assert_connection()
		return self.conn.execute(text(query), params)